const countryFlags: Record<string, string> = {
  'Mexico': '🇲🇽',
  'México': '🇲🇽',
  'South Africa': '🇿🇦',
  'Sudáfrica': '🇿🇦',
  'Korea Republic': '🇰🇷',
  'Corea del Sur': '🇰🇷',
  'Czechia': '🇨🇿',
  'Chequia': '🇨🇿',
  'Canada': '🇨🇦',
  'Canadá': '🇨🇦',
  'Bosnia and Herzegovina': '🇧🇦',
  'Bosnia y Herzegovina': '🇧🇦',
  'USA': '🇺🇸',
  'EE. UU.': '🇺🇸',
  'Paraguay': '🇵🇾',
  'Qatar': '🇶🇦',
  'Catar': '🇶🇦',
  'Switzerland': '🇨🇭',
  'Suiza': '🇨🇭',
  'Brazil': '🇧🇷',
  'Brasil': '🇧🇷',
  'Morocco': '🇲🇦',
  'Marruecos': '🇲🇦',
  'Haiti': '🇭🇹',
  'Haití': '🇭🇹',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Escocia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Australia': '🇦🇺',
  'Türkiye': '🇹🇷',
  'Turquía': '🇹🇷',
  'Germany': '🇩🇪',
  'Alemania': '🇩🇪',
  'Japan': '🇯🇵',
  'Japón': '🇯🇵',
  'Ivory Coast': '🇨🇮',
  'Costa de Marfil': '🇨🇮',
  'Ecuador': '🇪🇨',
  'Sweden': '🇸🇪',
  'Suecia': '🇸🇪',
  'Tunisia': '🇹🇳',
  'Túnez': '🇹🇳',
  'Spain': '🇪🇸',
  'España': '🇪🇸',
  'Cape Verde': '🇨🇻',
  'Cabo Verde': '🇨🇻',
  'Belgium': '🇧🇪',
  'Bélgica': '🇧🇪',
  'Egypt': '🇪🇬',
  'Egipto': '🇪🇬',
  'Saudi Arabia': '🇸🇦',
  'Arabia Saudita': '🇸🇦',
  'Uruguay': '🇺🇾',
  'IR Iran': '🇮🇷',
  'Irán': '🇮🇷',
  'New Zealand': '🇳🇿',
  'Nueva Zelanda': '🇳🇿',
  'France': '🇫🇷',
  'Francia': '🇫🇷',
  'Senegal': '🇸🇳',
  'Iraq': '🇮🇶',
  'Irak': '🇮🇶',
  'Norway': '🇳🇴',
  'Noruega': '🇳🇴',
  'Argentina': '🇦🇷',
  'Algeria': '🇩🇿',
  'Argelia': '🇩🇿',
  'Austria': '🇦🇹',
  'Jordan': '🇯🇴',
  'Jordania': '🇯🇴',
  'Portugal': '🇵🇹',
  'Congo DR': '🇨🇩',
  'R.D. del Congo': '🇨🇩',
  'England': '🏴',
  'Inglaterra': '🏴',
  'Croatia': '🇭🇷',
  'Croacia': '🇭🇷',
  'Ghana': '🇬🇭',
  'Panama': '🇵🇦',
  'Panamá': '🇵🇦',
  'Uzbekistan': '🇺🇿',
  'Uzbekistán': '🇺🇿',
  'Colombia': '🇨🇴'
};

const countryTranslations: Record<string, string> = {
  'Mexico': 'México',
  'South Africa': 'Sudáfrica',
  'Korea Republic': 'Corea del Sur',
  'Czechia': 'Chequia',
  'Canada': 'Canadá',
  'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
  'USA': 'EE. UU.',
  'Qatar': 'Catar',
  'Switzerland': 'Suiza',
  'Brazil': 'Brasil',
  'Morocco': 'Marruecos',
  'Haiti': 'Haití',
  'Scotland': 'Escocia',
  'Germany': 'Alemania',
  'Japan': 'Japón',
  'Ivory Coast': 'Costa de Marfil',
  'Sweden': 'Suecia',
  'Tunisia': 'Túnez',
  'Spain': 'España',
  'Cape Verde': 'Cabo Verde',
  'Belgium': 'Bélgica',
  'Egypt': 'Egipto',
  'Saudi Arabia': 'Arabia Saudita',
  'IR Iran': 'Irán',
  'New Zealand': 'Nueva Zelanda',
  'France': 'Francia',
  'Iraq': 'Irak',
  'Norway': 'Noruega',
  'Algeria': 'Argelia',
  'Jordan': 'Jordania',
  'Congo DR': 'R.D. del Congo',
  'England': 'Inglaterra',
  'Croatia': 'Croacia',
  'Panama': 'Panamá',
  'Uzbekistan': 'Uzbekistán'
};

export function getCountryFlag(team: string): string {
  const normalized = team.trim();
  return countryFlags[normalized] ? `${countryFlags[normalized]} ${team}` : team;
}

export function translateTeam(team: string, isEs: boolean): string {
  if (!isEs) return team;
  const normalized = team.trim();
  return countryTranslations[normalized] || team;
}
